### ISSUE TITLE
Material Icons so not work in Chrome on Android

### ISSUE THREAD

**Issue by ubergesundheit** [Leaflet/Leaflet.Icon.Glyph#1]
I just noticed that the markers are just empty blue. I visited the demo on a nexus 4 with Chrome 46

**Comment by IvanSanchez** [comment]
Confirmed - this is some weird Chrome bug involving how it loads resources. Just filed an upstream bug at google/material-design-icons#248.

If you really need these icons right now, I suggest hosting a copy of them by yourself.
