### ISSUE TITLE
Doesn't work 100% correctly with Font Awesome 5

### ISSUE THREAD

**Issue by krisalyssa** [Leaflet/Leaflet.Icon.Glyph#8]
Font Awesome 5 changed the way icons are prefixed: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

> Version 4 just had one prefix — fa. Version 5 has four prefixes to let us set the style of any icon easily:

The `fa` prefix still works for most icons, but:

* Some icons are brand logos, and now have the prefix `fab`
* The remaining icons now come in three weights; the two new weights have the prefixes `far` and `fal`.

Leaflet.Icon.Glyph assumes that the prefix will always be `fa`.

**Comment by IvanSanchez** [comment]
But the README and examples show how to specify your own prefixes. And the library itself doesn't assume any prefix, as per https://github.com/Leaflet/Leaflet.Icon.Glyph/blob/6a6d30bb611a04253382bec42d2e7bfef9009aeb/Leaflet.Icon.Glyph.js#L18

Am I missing something here?

**Comment by krisalyssa** [comment]
Leaflet.Icon.Glyph with Font Awesome 4:
```
var marker = L.marker(latlng, {
	icon: L.icon.glyph({
		prefix: 'fa',
		glyph: 'rocket'
	})
});
```

When using Leaflet.Icon.Glyph with Font Awesome 5:

* Setting `prefix` to `"fas"` and `glyph` to `"rocket"` doesn't work, because [line 48](https://github.com/Leaflet/Leaflet.Icon.Glyph/blob/gh-pages/Leaflet.Icon.Glyph.js#L48) will set `glyphClass` to `"fas fas-rocket"`.
* Setting `prefix` to `"fas"` and `glyph` to `"fa-rocket"` doesn't work, because the condition on [line 45](https://github.com/Leaflet/Leaflet.Icon.Glyph/blob/gh-pages/Leaflet.Icon.Glyph.js#L45) evaluates to false (because prefix length is 3, so the slice is `"fa-r"`), so code falls into the `else` clause, setting `glyphClass` to `"fas fas-fa-rocket"`.
* Setting `prefix` to `"fa"` and `glyph` to `"rocket"` still works, because FA 5 provides limited backward-compatibility with FA 4. However, that precludes being able to use any of the brand glyphs or (in the pro version) either of the other two weights.

I have a fix in mind, but have been a little too busy yesterday and today to be able to put together a PR. I'm off for the holidays starting tomorrow, so hopefully soon. 😄
